### PR TITLE
Date Elixir

### PR DESCRIPTION
**Pull request by fgallaire**

### CODE REVIEW

**Comment by llaisdy** [comment]
Wikipedia says 2012.

https://en.wikipedia.org/wiki/Elixir_(programming_language)

**Comment by fgallaire** [comment]
Your answer is really weird. You clearly misunderstood the Wikipedia principle. It is "correct if you find an error", not "promotes wrong informations because because Wikipedia is God".
https://github.com/elixir-lang/elixir/commit/337c3f2d569a42ebd5fcab6fef18c5e012f9be5b

**Comment by llaisdy** [comment]
If you think my answer is "really weird" you need to get out more.

**Comment by fgallaire** [comment]
Wikipedia now says 2011, so you can peacefully merge.

**Comment by llaisdy** [comment]
LOL

**Comment by fgallaire** [comment]
Please could you merge ?

**Pull request merged**
